### ISSUE TITLE
ArgumentError

### ISSUE THREAD

**Issue by pwen** [modeset/guard-teaspoon#30]
While runing guard-teaspoon, I'm getting the following error:

00:03:34 - ERROR - Guard::Teaspoon failed to achieve its <run_on_changes>, exception was:

> [#] ArgumentError: wrong number of arguments (2 for 0..1)
> [#] ../gems/teaspoon-0.8.0/lib/teaspoon/console.rb:20:in `execute`
> [#] ../gems/guard-teaspoon-0.0.4/lib/guard/teaspoon/runner.rb:26:in `run`

Gemfile.lock says:

```
guard (2.6.0)
  formatador (>= 0.2.4)
  listen (~> 2.7)
  lumberjack (~> 1.0)
  pry (>= 0.9.12)
  thor (>= 0.18.1)
guard-rails (0.5.0)
  guard (>= 2.0.0)
guard-rspec (4.2.8)
  guard (~> 2.1)
  rspec (>= 2.14, < 4.0)
guard-teaspoon (0.0.4)
  guard (>= 1.6.1)
  teaspoon (>= 0.5.3)
teaspoon (0.8.0)
  railties (>= 3.2.5, < 5)
```

**Comment by jbosse** [comment]
Hey, any movement on this?
