### ISSUE TITLE
error while running guard

### ISSUE THREAD

**Issue by brewster1134** [modeset/guard-teaspoon#38]
When running guard, i receive the error `Unexpected error while processing request: undefined method`debug' for nil:NilClass`.  here is the full trace and my gem details (pruned for brevity).

the nil class that throws the error is from `Rails.logger` being `nil`.  When i run the rails console in development, it exists.  I have tried with both ruby 1.9 and 2.1.2.  Is guard-teaspoon compatible with rails 4.1?

``` shell
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:52800, CTRL+C to stop
22:03:07 - INFO - Guard::Teaspoon is running
Teaspoon running default suite at http://127.0.0.1:52800/tests/default
Unexpected error while processing request: undefined method `debug' for nil:NilClass
  .../railties-4.1.6/lib/rails/rack/logger.rb:32:in `call_app'
  .../railties-4.1.6/lib/rails/rack/logger.rb:22:in `call'
  .../actionpack-4.1.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  .../rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  .../rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  .../rack-1.5.2/lib/rack/lock.rb:17:in `call'
  .../actionpack-4.1.6/lib/action_dispatch/middleware/static.rb:64:in `call'
  .../rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  .../railties-4.1.6/lib/rails/engine.rb:514:in `call'
  .../railties-4.1.6/lib/rails/application.rb:144:in `call'
  .../thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
  .../thin-1.6.3/lib/thin/connection.rb:84:in `catch'
  .../thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
  .../thin-1.6.3/lib/thin/connection.rb:53:in `process'
  .../thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
  .../eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
  .../eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
  .../thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
  .../thin-1.6.3/lib/thin/server.rb:162:in `start'
  .../rack-1.5.2/lib/rack/handler/thin.rb:16:in `run'
  .../rack-1.5.2/lib/rack/server.rb:264:in `start'
  .../teaspoon-0.8.0/lib/teaspoon/server.rb:18:in `block in start'

Failed to load: http://127.0.0.1:52800/tests/default?reporter=Console
22:03:08 - ERROR - Guard::Teaspoon failed to achieve its <start>, exception was:
> [#94AB78FBDCAC] SystemExit: exit
> [#94AB78FBDCAC] .../teaspoon-0.8.0/lib/teaspoon/console.rb:112:in `exit'
> [#94AB78FBDCAC] .../teaspoon-0.8.0/lib/teaspoon/console.rb:112:in `abort'
> [#94AB78FBDCAC] .../teaspoon-0.8.0/lib/teaspoon/console.rb:25:in `rescue in execute'
> [#94AB78FBDCAC] .../teaspoon-0.8.0/lib/teaspoon/console.rb:21:in `execute'
> [#94AB78FBDCAC] .../guard-teaspoon-0.8.0/lib/guard/teaspoon/runner.rb:21:in `run_all'
> [#94AB78FBDCAC] .../guard-teaspoon-0.8.0/lib/guard/teaspoon.rb:33:in `run_all'
> [#94AB78FBDCAC] .../guard-teaspoon-0.8.0/lib/guard/teaspoon.rb:29:in `start'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/runner.rb:74:in `block in run_supervised_task'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/runner.rb:71:in `catch'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/runner.rb:71:in `run_supervised_task'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/runner.rb:22:in `block (2 levels) in run'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/runner.rb:150:in `block (3 levels) in _scoped_plugins'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/runner.rb:148:in `each'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/runner.rb:148:in `block (2 levels) in _scoped_plugins'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/runner.rb:147:in `catch'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/runner.rb:147:in `block in _scoped_plugins'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/runner.rb:145:in `each'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/runner.rb:145:in `_scoped_plugins'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/runner.rb:21:in `block in run'
> [#94AB78FBDCAC] .../lumberjack-1.0.9/lib/lumberjack.rb:32:in `unit_of_work'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/runner.rb:20:in `run'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/commander.rb:28:in `block in start'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/commander.rb:108:in `block in within_preserved_state'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/commander.rb:105:in `synchronize'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/commander.rb:105:in `within_preserved_state'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/commander.rb:26:in `start'
> [#94AB78FBDCAC] .../guard-2.6.1/lib/guard/cli.rb:107:in `start'
> [#94AB78FBDCAC] .../thor-0.19.1/lib/thor/command.rb:27:in `run'
> [#94AB78FBDCAC] .../thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> [#94AB78FBDCAC] .../thor-0.19.1/lib/thor.rb:359:in `dispatch'
> [#94AB78FBDCAC] .../thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#94AB78FBDCAC] .../guard-2.6.1/bin/guard:6:in `<top (required)>'
> [#94AB78FBDCAC] /usr/local/var/rbenv/versions/2.1.2/bin/guard:23:in `load'
> [#94AB78FBDCAC] /usr/local/var/rbenv/versions/2.1.2/bin/guard:23:in `<main>'
22:03:08 - INFO - Guard::Teaspoon has just been fired
22:03:08 - INFO - Guard is now watching at '...'
```

``` ruby
gem 'rails', '~> 4.1.6'
gem 'thin', '~> 1.6.3'

group :development, :test do
  gem 'guard', '~> 2.6.1'
  gem 'guard-teaspoon', '~> 0.8.0'
  gem 'spring', '~> 1.1.3'
  gem 'teaspoon', '~> 0.8.0'
end
```

**Comment by rohitravikalra** [comment]
I am trying to run a rake task using guard-rake while watching a particular file.
Here's how my Guardfile looks like:

`guard 'rake', task: 'test_cases' do
  watch('abc/particular_file')
end`

Everytime I run guard it runs the task even if there is no change in the file it is watching over and secondly after showing me that it is running the task guard quits unexpectedly without showing any message. Here is my console output:

`
16:24:19 - INFO - Starting guard-rake test_cases
16:24:22 - INFO - running test_cases
rohitravikalra:~/Ruby On Rails/abc$ 
` 

Incase.. If you can help..?

Thanks
